### ISSUE TITLE
请问有没有人有训练完的模型

### ISSUE THREAD

**Issue by CanoeByGuitar** [AstarLight/Satellite-Segmentation#62]

**Comment by bianyuelin** [comment]
我有segnet用作者给的数据集训练好的模型

**Comment by CanoeByGuitar** [comment]
> 我有segnet用作者给的数据集训练好的模型

我是河海大学学生，不知能否邮件发我一下，仅做学习使用，十分感谢。我的邮箱是1781736691@qq.com

**Comment by zy1139069091** [comment]
我是安徽大学学生，能否给我也发一份，仅做学习使用，谢谢，我的邮箱是1139069091@qq.com

**Comment by YCamilla** [comment]
> 我有segnet用作者给的数据集训练好的模型
我是中南大学的学生，邮箱YCamilla@163.com，能麻烦您发我一下模型嘛～谢谢！

**Comment by ruidegithub** [comment]
> 我有segnet用作者给的数据集训练好的模型

你好！能提供一下训练好的模型吗，邮箱942909538@qq.com，谢谢！
