### ISSUE TITLE
unet_train.py訓練完一個epoch報錯ValueError('Unsupported image shape:',())

### ISSUE THREAD

**Issue by Angel0003** [AstarLight/Satellite-Segmentation#66]
爲啥我剛訓完一個epoch就報錯ValueError('Unsupported image shape:',())，誰能幫忙解決下，困擾很久了

**Comment by AmberrrLiu** [comment]
> 爲啥我剛訓完一個epoch就報錯ValueError('Unsupported image shape:',())，誰能幫忙解決下，困擾很久了

请问解决了吗
