### ISSUE TITLE
U-Net只能一次训练一个类别吗？

### ISSUE THREAD

**Issue by xjock** [AstarLight/Satellite-Segmentation#7]
如果一次训练一个类别，那么label数据可是包含5个类别，是不是需要处理一下呢？

unet_train.py我改动了一下

`classes_dict={1:'VEGETATION',2:'BUILDING',3:'WATER',4:'ROAD'}

def generateData(batch_size,classtype,data=[]):
    while True:
        train_data = []
        train_label = []
        batch = 0
        for i in (range(len(data))):
            url = data[i]
            batch += 1
            img = load_img(filepath + 'src/' + url)
            img = img_to_array(img)
            train_data.append(img)
            label = load_img(filepath + 'label/' + url, grayscale=True)
################################################################
            for key in classes_dict.keys():
                if(key != classtype):
                    mask=(label==key)
                    label[mask]=0
################################################################
            label = img_to_array(label)
            train_label.append(label)
            if batch % batch_size==0:
                train_data = np.array(train_data)
                train_label = np.array(train_label)
                yield (train_data,train_label)
                train_data = []
                train_label = []
                batch = 0

def generateValidData(batch_size,classtype,data=[]):
    while True:
        valid_data = []
        valid_label = []
        batch = 0
        for i in (range(len(data))):
            url = data[i]
            batch += 1
            img = load_img(filepath + 'src/' + url)
            img = img_to_array(img)
            valid_data.append(img)
            label = load_img(filepath + 'label/' + url, grayscale=True)
################################################################
            for key in classes_dict.keys():
                if(key != classtype):
                    mask=(label==key)
                    label[mask]=0
################################################################
            label = img_to_array(label)
            valid_label.append(label)
            if batch % batch_size==0:
                valid_data = np.array(valid_data)
                valid_label = np.array(valid_label)
                yield (valid_data,valid_label)
                valid_data = []
                valid_label = []
                batch = 0
`

**Comment by wuyang0329** [comment]
请问您改过之后的可以正常训练了吗
